---
author: "Kris Sankaran"
title: "Week6W"
output:
  xaringan::moon_reader:
    css: ["default", "css/xaringan-themer.css"]
    self_contained: false
    lib_dir: libs
    nature:
      ratio: "16:9"
    seal: false
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(tidyverse)
th <- theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    legend.position = "bottom"
  )
theme_set(th)
```

First, download and unzip this
[file](https://github.com/krisrs1128/stat479_s22/blob/main/_slides/week7/exercises/data/glacial_lakes.tar.gz).
For example, on mac / linux, run these lines in a terminal,

```{bash}
curl -L https://github.com/krisrs1128/stat479_s22/blob/main/_slides/week7/exercises/data/glacial_lakes.tar.gz?raw=true > glacial_lakes.tar.gz
tar -zxvf glacial_lakes.tar.gz
```

```{r}
library(tidyverse)
library(sf)
lakes <- read_sf("glacial_lakes/GL_3basins_2015.shp")
```
```{r}
lakes
```
a. 3264 lakes ottal

```{r}
lakes %>%
  group_by(Sub_Basin) %>%
  filter(Area == max(Area))
```
c.

- Filter the lakes to a smaller window: filter
- make the map: geom_sf
28.2 and 28.4
```{r}
filtered_lakes <- lakes %>%
  filter(
    Latitude > 28.2, Latitude < 28.4,
    Longitude > 85.8, Longitude < 86
  )

ggplot(filtered_lakes) +
  geom_sf(fill = "darkgrey", size = 0) +
  theme_void()
```

```{r}
library(ggmap)

filtered_lakes2 <- filtered_lakes %>%
  rename(lon = Longitude, lat = Latitude)

map <- get_stamenmap(c(85.8, 28.2, 86, 28.4))
ggmap(map) +
  geom_sf(data = filtered_lakes2[1:2, ], fill = "black", size = 0) +
  theme_void()
```

