---
author: "Kris Sankaran"
title: "Week7W Starter"
output:
  xaringan::moon_reader:
    css: ["default", "css/xaringan-themer.css"]
    self_contained: false
    lib_dir: libs
    nature:
      ratio: "16:9"
    seal: false
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(tidyverse)
th <- theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    legend.position = "bottom"
  )
theme_set(th)
```

```{r}
library(rnaturalearth) # needed for ne_countries
library(raster)
temperature <- raster("https://github.com/krisrs1128/stat479_s22/blob/main/_slides/week7/exercises/data/latest.grid?raw=true")
australia <- ne_countries(country = "australia")
```

```{r}
temp_df <- temperature %>%
  as.data.frame(xy = TRUE) %>%
  rename(temp = latest.grid.raw.true)

ggplot(temp_df) +
  geom_raster(aes(x, y, fill = temp)) +
  scale_fill_viridis_b(option = "inferno")
```

```{r}
library(sf)
australia <- st_as_sf(australia)
temp_subset <- mask(temperature, australia) %>%
  as.data.frame(xy = TRUE) %>%
  drop_na() %>%
  rename(temp = latest.grid.raw.true)
```
```{r}
temp_subset
```

```{r}
ggplot(temp_subset) +
  geom_raster(aes(x, y, fill = log(1  + temp))) +
  scale_fill_viridis_b(option = "inferno") +
  theme_void() +
  theme(legend.position = "bottom")
```
