---
author: ""
title: "Week8F Code Starter"
output:
  xaringan::moon_reader:
    css: ["default", "css/xaringan-themer.css"]
    self_contained: false
    lib_dir: libs
    nature:
      ratio: "16:9"
    seal: false
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(tidyverse)
th <- theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    legend.position = "bottom"
  )
theme_set(th)
```

```{r}
library(tidygraph)
library(ggraph)

nodes <- read_csv("https://raw.githubusercontent.com/krisrs1128/stat479_s22/main/_slides/week8/exercises/data/climate-nodes.csv")
edges <- read_csv("https://raw.githubusercontent.com/krisrs1128/stat479_s22/main/_slides/week8/exercises/data/climate-edges.csv")
### tbl_graph(...?)
```
```{r}
G <- tbl_graph(nodes, edges, directed = FALSE) %>%
  filter(row_number() < 100) %>%
  mutate(genre_group = fct_lump_n(genre, 8))

ggraph(G, "kk") +
  geom_edge_link() +
  geom_node_point(aes(col = genre_group, size = views)) +
  scale_radius(range = c(0.9, 10))

ggraph(G, layout = "matrix") +
  geom_edge_tile(aes(fill = type), mirror = TRUE) +
  geom_node_point(aes(size = views), x = -1) +
  geom_node_point(aes(size = views), y = -1) +
  coord_fixed()
```

