---
title: '20220218'
author: "Cameron Jones"
date: "2/18/2022"
output: html_document
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(plotly)
theme_set(theme_minimal())

# download and find a good ordering of the counties
fires <- read_csv("https://uwmadison.box.com/shared/static/k5vvekf1bhh9e16qb9s66owygc70t7dm.csv")
county_order <- fires %>%
  group_by(Counties) %>%
  summarise(latitude = median(Latitude)) %>% 
  arrange(latitude) %>%
  pull(Counties)

#' Function for making static plots
#' example usage:
#' fires %>%
#'   mutate(selected = year == 2018) %>%
#'   plot_fires()
plot_fires <- function(df) {
  p <- ggplot(df, aes(day_of_year, reorder(Counties, Latitude), size = AcresBurned)) +
    geom_point(data = df %>% filter(!selected), col = "#d3d3d3") +
    geom_point(data = df %>% filter(selected), aes(text = Name), col = "orange") +
    scale_y_discrete(limits = county_order)
  ggplotly(p)
}
```

### a) Static Graph

```{r}
ggplot(fires) +
  geom_point(aes(x = day_of_year, y = Counties, size = AcresBurned))
```

### b) Interactive Graph With Extra UI Input (Data Table)

```{r}
ui <- fluidPage(
  sliderInput("range", "Years Selected:",
                  min = 2013, max = 2018,
                  value = c(2013,2018)),
  plotlyOutput("fires_plot"),
  dataTableOutput("fires_df")
)

server <- function(input, output) {
  fires_subset = reactive({
    fires %>% 
      mutate(selected = (year >= input$range[1] & year<= input$range[2]))
  })
  output$fires_plot = renderPlotly({
    plot_fires(fires_subset())
  })
  output$fires_df = renderDataTable({
    fires_subset() %>%
      filter(selected)
  })
}
shinyApp(ui,server)
```

