---
author: "Kris Sankaran"
title: "Week9F"
output:
  xaringan::moon_reader:
    css: ["default", "css/xaringan-themer.css"]
    self_contained: false
    lib_dir: libs
    nature:
      ratio: "16:9"
    seal: false
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(tidyverse)
opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE, dpi = 200, fig.align = "center", out.width = 650, fig.height = 3, fig.width = 9)
th <- theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    legend.position = "bottom"
  )
theme_set(th)
options(width = 100)
```
class: bottom

# Heatmap Visualizations

.pull-left[
  April 1, 2022
]
 
---

### Today

By the end of the class, you should be able to...

   * Construct and interpret a heatmap with rows and columns sorted by a
   hierarchical clustering
   * Use principles from compound figures to supplement a basic heatmap

---

### Exercise Review

[Interpreting Clustering] Imagine that you are a statistical consultant
working with a scientist / sports team / journalist / sales division head (pick
your favorite or make up your own example). At one point in your study, you
found it useful to apply various types of clustering methods. In this problem,
you are asked to provide a non-technical explanation of how to interpret your
clustering output, assuming that your audience is familiar with their data but
not statistical methodology.

* For concreteness, let's consider the Beijing weather / pollution data
* Imagine we are working with metereology experts who understand the details of
data collection

---

a. You have run $K$-means with $K = 5$ clusters across their dataset, which
includes $50$ different measurements for each row. Explain to your audience
what each centroid represents.

*  Each row in our clustering included 24 hours worth of measurements for
temperature, wind speed, and pollution
* Since we clustered rows, this means each cluster is a collection of days with
similar weather and pollution time series
* $\implies$ Each centroid is the "typical" day of weather / pollution among all
days within that cluster
  - We've found 5 weather profiles that are representative of all the variation
  we've seen across the dataset

---

b. At another point, you applied hierarchical clustering to the same
dataset. You include a visualization of the hierarchical clustering tree in
your report. Provide a brief, non-technical explanation of how to interpret
the tree.

* Each leaf in the tree is a single day in the dataset
* Days that lie on the same subtree have similar 24-hour patterns of
temperature, wind speed, and pollution
    - More recent common ancestors $\implies$ more similar days
* Well-defined subtrees have more distinctive profiles

---

c. Your audience finds the hierarchical clustering tree, but wonders why you
needed a new algorithm to produce it. They think that you would have gotten
similar results if you had simply run $K$-means with different values of
$K$. Respond to their observations.

* The results would be similar, but with $K$-means, the clusters would not
necessarily be "nested" within one another
* In hierarchical clustering, the clusters we get from $K = 5$ are all subsets
of clusters we get at $K = 4$.

---

## Live Coding Example

We will work through Exercise 2 in Module 3.

---

### Exercise

* Exercise 9.2 [Interpreting Clustering] on Canvas
* Can discuss, but submit individually