---
author: "Kris Sankaran"
title: "week3F"
output:
  xaringan::moon_reader:
    css: ["default", "css/xaringan-themer.css"]
    self_contained: false
    lib_dir: libs
    nature:
      ratio: "16:9"
    seal: false
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(tidyverse)
opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE, dpi = 200, fig.align = "center", out.width = 650)
th <- theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    legend.position = "bottom"
  )
theme_set(th)
options(width = 100)
```
class: bottom

# Compound Figures Review

.pull-left[
February 11, 2022
]
 
---

### Announcements

 
---

### Exercise 3.2 Discussion

---

## Muddiest Points

* When is a dataset tidy?
* When we receive a dataset, how should we re-arrange the rows and columns?

---

1. Often, "tidyness" depends on the purpose of the analysis. 
1. Each mark on the page should correspond to a single row in the input
`data.frame`, but this may vary from figure to figure.
  - In a survey, we can tidy so that each survey respondent is in a row
  and questions are along columns (so $n$ rows, one per respondent).
  - Alternatively, we can reshape it so that each question response gets its own
  rows (so $n \times Q$ rows, one per respondent-question pair).

---

1. In practice, create one folder with the raw data. Never touch this folder.
1. Prepare a script to generate a few versions of the "derived" data. These can
be tidied into several forms.
  - One derived dataset with respondents on rows
  - Another with question responses on rows
1. Downstream visualizations can refer to either derived dataset

---

### Notes review

(go to [link]()

---

### Exercise

* Exercise 3.3 on Canvas
* Discuss in groups, but submit own solution
* Until: 
